name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements-docs.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Build and deploy docs to GitHub Pages
        run: mkdocs gh-deploy --force --clean
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
